import { Inter } from 'next/font/google';
import './globals.css';
import Nav from '@/components/Nav';

export const metadata = {
	title: 'gigMe app',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	const isLogged = false;
	return (
		<html lang="en">
			<body>
				<Nav />
				<div className="min-h-screen justify-center items-center ">
					{children}
				</div>
			</body>
		</html>
	);
}
