import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import { GlobalProvider } from "./Context/store";
import { NextAuthProvider } from "./Providers";
export const metadata = {
  title: "gigMe app",
  description: "Generated by create next app",
};

export default function RootLayout({ children, modal }) {
  return (
    <html lang="en">
      <body>
        <div className="w-full justify-center items-center ">
          <NextAuthProvider>
            <GlobalProvider>
              <div className="flex">
                {modal}
                {children}
              </div>
            </GlobalProvider>
          </NextAuthProvider>
        </div>
      </body>
    </html>
  );
}
